TRUNCATE topics CASCADE;
TRUNCATE notes CASCADE;
TRUNCATE weeks CASCADE;

INSERT INTO weeks (week_number, module, title, status) VALUES
  (1,  'python-llm', 'Python基础 + FastAPI + AI环境搭建', 'active'),
  (2,  'python-llm', 'LLM基础 + Prompt Engineering', 'pending'),
  (3,  'rag', 'LangChain + 聊天助手V2', 'pending'),
  (4,  'rag', 'Embedding + 向量数据库 + 模型微调入门', 'pending'),
  (5,  'rag', 'RAG基础 + 企业知识库V1', 'pending'),
  (6,  'skill', 'RAG收口 + 金融机构接入Skill设计', 'pending'),
  (7,  'skill', '金融机构接入Skill V0.1', 'pending'),
  (8,  'skill', '金融机构接入Skill V1', 'pending'),
  (9,  'guardian', 'AI智能守护 V0.1', 'pending'),
  (10, 'guardian', 'AI智能守护 V1', 'pending'),
  (11, 'career', 'Java + AI面试冲刺', 'pending'),
  (12, 'career', '面试反馈 + Offer冲刺', 'pending');

INSERT INTO topics (week_id, name, completed, topic_order)
SELECT w.id, t.name, false, t.ord
FROM weeks w
JOIN (VALUES
  (1, '周一 Python核心语法 (2h)', 1),
  (1, '周二 Python面向对象+异步编程 (2h)', 2),
  (1, '周三 FastAPI基础 (2h)', 3),
  (1, '周四 请求响应+流式输出 (2h)', 4),
  (1, '周五 AI API调用 (2h)', 5),
  (1, '周六 FastAPI综合+项目搭建 (6h)', 6),
  (1, '周日 项目复盘+GitHub整理 (6h)', 7),
  (2, '周一 Token/Embedding/语义向量 (2h)', 1),
  (2, '周二 Transformer+Attention机制 (2h)', 2),
  (2, '周三 Prompt基础 (2h)', 3),
  (2, '周四 Few-shot/CoT/防御注入 (2h)', 4),
  (2, '周五 Structured Output+JSON (2h)', 5),
  (2, '周六 幻觉控制+Temperature+System Prompt (6h)', 6),
  (2, '周日 Prompt库整理+项目集成 (6h)', 7),
  (3, '周一 LangChain基础+PromptTemplate (2h)', 1),
  (3, '周二 LCEL表达式+Chains (2h)', 2),
  (3, '周三 Memory机制 (2h)', 3),
  (3, '周四 OutputParser+Function Calling (2h)', 4),
  (3, '周五 聊天助手增强+持久化 (2h)', 5),
  (3, '周六 Function Calling完整实现 (6h)', 6),
  (3, '周日 项目部署+GitHub整理 (6h)', 7),
  (4, '周一 Embedding原理+语义检索 (2h)', 1),
  (4, '周二 向量数据库基础CRUD (2h)', 2),
  (4, '周三 Chroma实战+向量存储 (2h)', 3),
  (4, '周四 模型微调入门：LoRA原理+Hugging Face (2h)', 4),
  (4, '周五 文本切分策略+优化 (2h)', 5),
  (4, '周六 PDF/Word解析+批量处理 (6h)', 6),
  (4, '周日 LoRA微调实战：准备数据+训练模型 (6h)', 7),
  (5, '周一 RAG整体流程 (2h)', 1),
  (5, '周二 PDF/多格式文档解析 (2h)', 2),
  (5, '周三 Chunk优化+阈值过滤 (2h)', 3),
  (5, '周四 Embedding接入+向量检索 (2h)', 4),
  (5, '周五 检索拼装Prompt+生成回答 (2h)', 5),
  (5, '周六 企业知识库V1开发+引用标注 (6h)', 6),
  (5, '周日 阶段复盘+Bad Case整理 (6h)', 7),
  (6, '周一 Day29/30 D+7 + RAG全链路集成 (7h)', 1),
  (6, '周二 Day31 D+7 + 端到端检索 (7h)', 2),
  (6, '周三 Day32 D+7 + Bad Case (7h)', 3),
  (6, '周四 Day33 D+7 + RAG阶段验收 (7h)', 4),
  (6, '周五 Skill需求与业务边界 (7h)', 5),
  (6, '周六 自造文档与标准领域模型 (4h)', 6),
  (6, '周日 项目规则、架构与验收冻结 (4h)', 7),
  (7, '周一 PDF/Word/Excel统一解析 (7h)', 1),
  (7, '周二 Structured Output + JSON Schema (7h)', 2),
  (7, '周三 标准领域模型 + RAG索引 (7h)', 3),
  (7, '周四 元数据、版本与引用 (7h)', 4),
  (7, '周五 字段映射与差异识别 (7h)', 5),
  (7, '周六 评估集 + V0.1集成 (4h)', 6),
  (7, '周日 README、演示与投递准备 (4h)', 7),
  (8, '周一 Skill结构与渐进式上下文 (7h)', 1),
  (8, '周二 Tool Calling + LangGraph (7h)', 2),
  (8, '周三 Human-in-the-loop (7h)', 3),
  (8, '周四 配置 + Java适配器骨架生成 (7h)', 4),
  (8, '周五 Maven编译 + 契约测试 (7h)', 5),
  (8, '周六 端到端验收 + 评估 (4h)', 6),
  (8, '周日 作品集材料 + 面试投递 (4h)', 7),
  (9, '周一 指标与决策模型 (7h)', 1),
  (9, '周二 Sentinel/Hippo4j与安全边界 (7h)', 2),
  (9, '周三 指标模拟与历史回放 (7h)', 3),
  (9, '周四 专家规则引擎 (7h)', 4),
  (9, '周五 策略校验与审计 (7h)', 5),
  (9, '周六 模拟控制面 V0.1 (4h)', 6),
  (9, '周日 V0.1复盘 + 项目面试 (4h)', 7),
  (10, '周一 治理RAG知识库 (7h)', 1),
  (10, '周二 策略建议Agent + LangGraph (7h)', 2),
  (10, '周三 硬性安全闸门 (7h)', 3),
  (10, '周四 模拟执行 + Human-in-the-loop (7h)', 4),
  (10, '周五 灰度、观测与回滚 (7h)', 5),
  (10, '周六 评估集与Bad Case (4h)', 6),
  (10, '周日 文档、演示与面试 (4h)', 7),
  (11, '周一 Java核心、JVM、并发 (7h)', 1),
  (11, '周二 Spring、MySQL、Redis、MQ (7h)', 2),
  (11, '周三 RAG、Skill与评估 (7h)', 3),
  (11, '周四 Agent、智能守护与系统设计 (7h)', 4),
  (11, '周五 算法、编码与故障定位 (7h)', 5),
  (11, '周六 Java + AI综合模拟面试 (4h)', 6),
  (11, '周日 简历、GitHub与投递复盘 (4h)', 7),
  (12, '周一 面试反馈定向复习 (7h)', 1),
  (12, '周二 限时编码 + 系统设计 (7h)', 2),
  (12, '周三 两个作品集深挖 (7h)', 3),
  (12, '周四 Java + AI综合模拟 (7h)', 4),
  (12, '周五 投递跟进与岗位定向准备 (7h)', 5),
  (12, '周末 真实面试、反馈与修正 (8h)', 6),
  (12, '9.14–9.15 最终跟进、Offer比较与总复盘 (11h)', 7)
) AS t(week_number, name, ord) ON w.week_number = t.week_number;
