TRUNCATE topics CASCADE;
TRUNCATE notes CASCADE;
TRUNCATE weeks CASCADE;

INSERT INTO weeks (week_number, module, title, status) VALUES
  (1,  'dev', 'Python基础 + FastAPI + AI环境搭建', 'active'),
  (2,  'dev', 'LLM基础 + Prompt Engineering', 'pending'),
  (3,  'dev', 'LangChain + 聊天助手V2', 'pending'),
  (4,  'dev', 'Embedding + 向量数据库', 'pending'),
  (5,  'dev', 'RAG基础 + 企业知识库V1', 'pending'),
  (6,  'dev', 'RAG优化 + 金融领域知识库', 'pending'),
  (7,  'dev', 'Function Calling + Tool Agent', 'pending'),
  (8,  'dev', 'Agent + Excel数据分析', 'pending'),
  (9,  'dev', 'LangGraph + Workflow', 'pending'),
  (10, 'eng', 'AI工程化 + Docker部署', 'pending'),
  (11, 'pm', '项目整理 + 面试冲刺', 'pending'),
  (12, 'pm', 'AI产品能力 + 复盘', 'pending');

INSERT INTO topics (week_id, name, completed, topic_order)
SELECT w.id, t.name, false, t.ord
FROM weeks w
JOIN (VALUES
  (1, '周一 Python核心语法 (2h)', 1),
  (1, '周二 Python面向对象+异步编程 (2h)', 2),
  (1, '周三 FastAPI基础 (2h)', 3),
  (1, '周四 请求响应+流式输出 (2h)', 4),
  (1, '周五 Docker基础+AI API调用 (2h)', 5),
  (1, '周六 FastAPI综合+项目搭建 (6h)', 6),
  (1, '周日 项目复盘+Docker打包+GitHub (6h)', 7),
  (2, '周一 Token/Embedding/语义向量 (2h)', 1),
  (2, '周二 Transformer+Attention机制 (2h)', 2),
  (2, '周三 Prompt基础 (2h)', 3),
  (2, '周四 Few-shot/CoT/防御注入 (2h)', 4),
  (2, '周五 Structured Output+JSON (2h)', 5),
  (2, '周六 幻觉控制+Temperature+System Prompt (6h)', 6),
  (2, '周日 Prompt库整理+项目集成 (6h)', 7),
  (3, '周一 LangChain基础+PromptTemplate (2h)', 1),
  (3, '周二 LCEL表达式+Chains (2h)', 2),
  (3, '周三 Memory机制 (2h)', 3),
  (3, '周四 OutputParser+Function Calling (2h)', 4),
  (3, '周五 聊天助手增强+持久化 (2h)', 5),
  (3, '周六 Function Calling完整实现 (6h)', 6),
  (3, '周日 项目部署+GitHub整理 (6h)', 7),
  (4, '周一 Embedding原理+语义检索 (2h)', 1),
  (4, '周二 向量数据库基础CRUD (2h)', 2),
  (4, '周三 Chroma实战+向量存储 (2h)', 3),
  (4, '周四 pgvector+混合存储 (2h)', 4),
  (4, '周五 文本切分策略 (2h)', 5),
  (4, '周六 PDF/Word解析+批量处理 (6h)', 6),
  (4, '周日 知识库数据准备+索引构建 (6h)', 7),
  (5, '周一 RAG整体流程 (2h)', 1),
  (5, '周二 PDF/多格式文档解析 (2h)', 2),
  (5, '周三 Chunk优化+阈值过滤 (2h)', 3),
  (5, '周四 Embedding接入+向量检索 (2h)', 4),
  (5, '周五 检索拼装Prompt+生成回答 (2h)', 5),
  (5, '周六 企业知识库V1开发+引用标注 (6h)', 6),
  (5, '周日 阶段复盘+Bad Case整理 (6h)', 7),
  (6, '周一 Hybrid Search混合检索 (2h)', 1),
  (6, '周二 Rerank重排序 (2h)', 2),
  (6, '周三 Query Rewrite+多轮问答 (2h)', 3),
  (6, '周四 金融文档整理+术语库 (2h)', 4),
  (6, '周五 金融Prompt+权限设计 (2h)', 5),
  (6, '周六 金融RAG完善+GraphRAG (6h)', 6),
  (6, '周日 录屏演示+文档输出 (6h)', 7),
  (7, '周一 Function Calling规范 (2h)', 1),
  (7, '周二 Tool Schema+参数规范 (2h)', 2),
  (7, '周三 稳定JSON+参数解析 (2h)', 3),
  (7, '周四 天气API工具Agent (2h)', 4),
  (7, '周五 搜索/汇率查询工具 (2h)', 5),
  (7, '周六 多工具并行/串行调用 (6h)', 6),
  (7, '周日 Agent项目整理+部署 (6h)', 7),
  (8, '周一 ReAct Agent (2h)', 1),
  (8, '周二 Agent长期Memory (2h)', 2),
  (8, '周三 Planning+任务拆解 (2h)', 3),
  (8, '周四 Pandas+Excel解析 (2h)', 4),
  (8, '周五 Code Interpreter+沙箱 (2h)', 5),
  (8, '周六 数据分析Agent+自动报告 (6h)', 6),
  (8, '周日 Agent复盘+难点整理 (6h)', 7),
  (9, '周一 LangGraph状态机 (2h)', 1),
  (9, '周二 Workflow设计+条件分支 (2h)', 2),
  (9, '周三 Dify低代码实践 (2h)', 3),
  (9, '周四 MCP+企业流程规范 (2h)', 4),
  (9, '周五 工单识别→分类→处理 (2h)', 5),
  (9, '周六 工单Agent+消息通知 (6h)', 6),
  (9, '周日 工作流优化+简历描述 (6h)', 7),
  (10, '周一 Docker进阶+docker-compose (2h)', 1),
  (10, '周二 Redis缓存+降Token成本 (2h)', 2),
  (10, '周三 日志系统+Loguru+LangSmith (2h)', 3),
  (10, '周四 Token成本优化+调用节流 (2h)', 4),
  (10, '周五 Nginx反向代理+HTTPS (2h)', 5),
  (10, '周六 云服务器上线+Linux (6h)', 6),
  (10, '周日 系统压测+并发优化 (6h)', 7),
  (11, '周一 项目文档+技术方案 (2h)', 1),
  (11, '周二 架构图+流程绘图 (2h)', 2),
  (11, '周三 AI产品案例+需求分析 (2h)', 3),
  (11, '周四 AI高频面试题 (2h)', 4),
  (11, '周五 简历优化+STAR法则 (2h)', 5),
  (11, '周六 模拟面试+GitHub美化 (6h)', 6),
  (11, '周日 最终发布+求职开启 (6h)', 7),
  (12, '周一 AI产品需求分析 (2h)', 1),
  (12, '周二 AI产品设计+交互 (2h)', 2),
  (12, '周三 AI产品数据+商业化 (2h)', 3),
  (12, '周四 AI产品用户体验 (2h)', 4),
  (12, '周五 跨职能协作+技术沟通 (2h)', 5),
  (12, '周六 90天全流程复盘 (6h)', 6),
  (12, '周日 成果整理+持续学习 (6h)', 7)
) AS t(week_number, name, ord) ON w.week_number = t.week_number;
