TRUNCATE topics CASCADE;
TRUNCATE notes CASCADE;
TRUNCATE weeks CASCADE;

INSERT INTO weeks (week_number, module, title, status) VALUES
  (1,  'python-llm', 'Python基础 + FastAPI + AI环境搭建', 'done'),
  (2,  'python-llm', 'LLM基础 + Prompt Engineering', 'done'),
  (3,  'rag', 'LangChain + 聊天助手V2', 'done'),
  (4,  'rag', 'Embedding + 向量数据库 + 文档处理基础', 'done'),
  (5,  'rag', 'RAG工程基础（已完成）', 'done'),
  (6,  'skill', '金融机构接入Skill：最小业务闭环', 'done'),
  (7,  'skill', '金融机构接入Skill：三模式AI直写闭环', 'done'),
  (8,  'skill', '金融机构接入Skill V1发布 + 首批投递', 'active'),
  (9,  'guardian', 'AI智能守护 V0.1', 'pending'),
  (10, 'guardian', 'AI智能守护 V1', 'pending'),
  (11, 'career', 'Java + AI面试冲刺', 'pending'),
  (12, 'career', '面试反馈 + Offer冲刺', 'pending');

INSERT INTO topics (week_id, name, completed, topic_order)
SELECT w.id, t.name, t.completed, t.ord
FROM weeks w
JOIN (VALUES
  (1, '周一 Python核心语法 (2h)', true, 1),
  (1, '周二 Python面向对象+异步编程 (2h)', true, 2),
  (1, '周三 FastAPI基础 (2h)', true, 3),
  (1, '周四 请求响应+流式输出 (2h)', true, 4),
  (1, '周五 AI API调用 (2h)', true, 5),
  (1, '周六 FastAPI综合+项目搭建 (6h)', true, 6),
  (1, '阶段收口 仓库整理并入作品集发布 (0h)', true, 7),
  (2, '周一 Token/Embedding/语义向量 (2h)', true, 1),
  (2, '周二 Transformer+Attention机制 (2h)', true, 2),
  (2, '周三 Prompt基础：Role/Task/Context/Output (2h)', true, 3),
  (2, '周四 Few-shot/CoT/防御Prompt注入 (2h)', true, 4),
  (2, '周五 Structured Output+稳定JSON (2h)', true, 5),
  (2, '周六 幻觉控制+Temperature+System Prompt (6h)', true, 6),
  (2, '阶段收口 提示词资产并入作品集 (0h)', true, 7),
  (3, '周一 LangChain基础+PromptTemplate (2h)', true, 1),
  (3, '周二 LCEL表达式+Chains链路 (2h)', true, 2),
  (3, '周三 Memory机制 (2h)', true, 3),
  (3, '周四 OutputParser+Function Calling (2h)', true, 4),
  (3, '周五 聊天助手增强+记录持久化 (2h)', true, 5),
  (3, '周六 Function Calling完整实现 (6h)', true, 6),
  (3, '阶段收口 部署任务取消 (0h)', true, 7),
  (4, '周一 Embedding原理+语义检索 (2h)', true, 1),
  (4, '周二 向量数据库基础CRUD (2h)', true, 2),
  (4, '周三 Chroma实战+向量存储 (2h)', true, 3),
  (4, '周四 模型微调入门：LoRA原理+Hugging Face (2h)', true, 4),
  (4, '周五 文本切分策略+优化 (2h)', true, 5),
  (4, '周六 PDF/Word解析+批量处理 (6h)', true, 6),
  (4, '阶段收口 LoRA实战暂缓（非待办） (0h)', true, 7),
  (5, '周一 RAG整体流程 (2h)', true, 1),
  (5, '周二 PDF/多格式文档解析 (2h)', true, 2),
  (5, '周三 Chunk优化+阈值过滤 (2h)', true, 3),
  (5, '周四 Embedding接入+向量检索 (2h)', true, 4),
  (5, '周五 检索拼装Prompt+生成回答 (2h)', true, 5),
  (5, '阶段验收 Day36 RAG全链路集成 (7h)', true, 6),
  (6, '周一 Day36 RAG全链路验收（已完成） (7h)', true, 1),
  (6, '周二 脚手架审查 + V0.1验收冻结 (7h)', true, 2),
  (6, '周三 三个虚构机构的多格式文档 (7h)', true, 3),
  (6, '周四 统一解析器 + ParseResult (7h)', true, 4),
  (6, '周五 标准文档块 + 数据质量闸门 + 解析校验 (7h)', true, 5),
  (6, '周六 结构化抽取契约（AI环节） (4h)', true, 6),
  (6, '周日 最小纵向闭环 + 自动测试 (4h)', true, 7),
  (7, '周一 标准字段映射 (7h)', true, 1),
  (7, '周二 差异、冲突与待确认项 (7h)', true, 2),
  (7, '周三 带范围过滤的RAG证据检索 (7h)', true, 3),
  (7, '周四 证据编号 + 人工确认状态流 (7h)', true, 4),
  (7, '周五 LLM直写完整Java SPI (7h)', true, 5),
  (7, '周六 Maven编译 + 契约测试 (4h)', true, 6),
  (7, '周日 V0.1集成 + 黄金集评估 (4h)', true, 7),
  (8, '周一 完整链路集成 + 错误恢复 (7h)', false, 1),
  (8, '周二 黄金集 + 量化评估 (7h)', false, 2),
  (8, '周三 Bad Case修复 + 首批投递 (7h)', false, 3),
  (8, '周四 README + 架构图 + 演示脚本 (7h)', false, 4),
  (8, '周五 V1候选版本验收 (7h)', false, 5),
  (8, '周六 项目演示 + 简历项目描述 (4h)', false, 6),
  (8, '周日 发布复盘 + 定向投递 (4h)', false, 7),
  (9, '周一 独立仓库 + 指标决策模型 (7h)', false, 1),
  (9, '周二 模拟指标 + 事件回放 (7h)', false, 2),
  (9, '周三 专家规则引擎 (7h)', false, 3),
  (9, '周四 优先级、冲突、冷却与防抖 (7h)', false, 4),
  (9, '周五 安全校验 + 审计状态 (7h)', false, 5),
  (9, '周六 命令行或API演示 (4h)', false, 6),
  (9, '周日 确定性基线评估 (4h)', false, 7),
  (10, '周一 Agent边界 + 状态流 (7h)', false, 1),
  (10, '周二 指标、规则与历史事件工具 (7h)', false, 2),
  (10, '周三 专家经验RAG知识库 (7h)', false, 3),
  (10, '周四 分析→建议→解释Agent (7h)', false, 4),
  (10, '周五 硬闸门 + 人工审批 + 回滚 (7h)', false, 5),
  (10, '周六 事件回放 + 对比评估 (4h)', false, 6),
  (10, '周日 V1文档、演示与发布 (4h)', false, 7),
  (11, '周一 简历反馈 + 两个项目叙事 (7h)', false, 1),
  (11, '周二 Java核心、JVM与并发 (7h)', false, 2),
  (11, '周三 Spring、事务与数据中间件 (7h)', false, 3),
  (11, '周四 资金网关 + AI系统设计 (7h)', false, 4),
  (11, '周五 RAG、Agent、评估与安全 (7h)', false, 5),
  (11, '周六 编码题 + 综合模拟面试 (4h)', false, 6),
  (11, '周日 简历、作品集与投递漏斗修正 (4h)', false, 7),
  (12, '周一 真实反馈分类 + 缺口排序 (7h)', false, 1),
  (12, '周二 最高优先级短板补强 (7h)', false, 2),
  (12, '周三 定向模拟面试 (7h)', false, 3),
  (12, '周四 在途流程跟进 + 定向补投 (7h)', false, 4),
  (12, '周五 系统设计 + 项目终面表达 (7h)', false, 5),
  (12, '周末 真实面试 + 24小时复盘 (8h)', false, 6),
  (12, '9.14–9.15 最终流程推进 + 决策复盘 (11h)', false, 7)
) AS t(week_number, name, completed, ord) ON w.week_number = t.week_number;
